-- Dim_Store with deduplication to avoid duplicates
MERGE INTO ECOMMERCE_DB.STAR_SCHEMA.DIM_STORE tgt
USING (
    WITH stores_deduped AS (
        SELECT 
            STORE_ID,
            STORE_NAME,
            CITY AS STORE_CITY,
            ADDRESS AS STORE_ADDRESS,
            MANAGER AS MANAGER_NAME,
            ROW_NUMBER() OVER (PARTITION BY STORE_ID ORDER BY STORE_ID) AS rn
        FROM ECOMMERCE_DB.ECOMMERCE_SCHEMA.STORES
    )
    SELECT STORE_ID, STORE_NAME, STORE_CITY, STORE_ADDRESS, MANAGER_NAME
    FROM stores_deduped
    WHERE rn = 1
) src
ON tgt.STORE_ID = src.STORE_ID
WHEN MATCHED THEN UPDATE SET
    STORE_NAME = src.STORE_NAME,
    STORE_CITY = src.STORE_CITY,
    STORE_ADDRESS = src.STORE_ADDRESS,
    MANAGER_NAME = src.MANAGER_NAME
WHEN NOT MATCHED THEN INSERT (
    STORE_ID, STORE_NAME, STORE_CITY, STORE_ADDRESS, MANAGER_NAME
) VALUES (
    src.STORE_ID, src.STORE_NAME, src.STORE_CITY, src.STORE_ADDRESS, src.MANAGER_NAME
);
