MERGE INTO ECOMMERCE_DB.STAR_SCHEMA.DIM_RETURN tgt
USING (
    SELECT 
        RETURN_ID,
        RETURN_REASON AS RETURN_REASON_CATEGORY,
        CASE WHEN REFUND_AMOUNT > 0 THEN 'Y' ELSE 'N' END AS IS_REFUNDABLE,
        CASE 
            WHEN rand_val < 0.33 THEN 2
            WHEN rand_val < 0.66 THEN 4
            ELSE 8
        END AS EXPECTED_RESOLUTION_TIME_DAYS,
        CASE 
            WHEN rand_val < 0.33 THEN 'low'
            WHEN rand_val < 0.66 THEN 'medium'
            ELSE 'high'
        END AS PRIORITY_LEVEL
    FROM (
        SELECT
            RETURN_ID,
            RETURN_REASON,
            REFUND_AMOUNT,
            RANDOM() AS rand_val,
            ROW_NUMBER() OVER (PARTITION BY RETURN_ID ORDER BY RETURN_ID) AS rn
        FROM ECOMMERCE_DB.ECOMMERCE_SCHEMA.RETURNS
    ) dedup_returns
    WHERE rn = 1
) src
ON tgt.RETURN_ID = src.RETURN_ID
WHEN MATCHED THEN UPDATE SET
    RETURN_REASON_CATEGORY = src.RETURN_REASON_CATEGORY,
    IS_REFUNDABLE = src.IS_REFUNDABLE,
    EXPECTED_RESOLUTION_TIME_DAYS = src.EXPECTED_RESOLUTION_TIME_DAYS,
    PRIORITY_LEVEL = src.PRIORITY_LEVEL
WHEN NOT MATCHED THEN INSERT (
    RETURN_ID, RETURN_REASON_CATEGORY, IS_REFUNDABLE, EXPECTED_RESOLUTION_TIME_DAYS, PRIORITY_LEVEL
) VALUES (
    src.RETURN_ID, src.RETURN_REASON_CATEGORY, src.IS_REFUNDABLE, src.EXPECTED_RESOLUTION_TIME_DAYS, src.PRIORITY_LEVEL
);
